<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>reg</title>
</head>
<body>
	<form action="/api/passport/reg" id="frmLogin" name="frmLogin" method="post">
		用户名:<input type="text" name="username" id="username"><br>
		密码：<input type="text" name="password" id="password"><br>
		确认密码：<input type="text" name="re_password" id="re_password"><br>
		手机号码：<input type="text" name="mobile" id="mobile"><br>
		手机验证码：<input type="text" name="verify" id="verify">默认9999<br>
		<input type="submit" name="s1" id="s1" value="提交">
	</form>
</body>
</html>